### ISSUE TITLE
I'm struggling with the model reproduction.

### ISSUE THREAD

**Issue by hybyun0121** [CRIPAC-DIG/MICRO#1]
Hi.

Fist of all, thank you for you guys opened this repository.
I learned alot with the paper and this code.  
  

![image](https://user-images.githubusercontent.com/63500940/165427829-9bef08de-bea5-46ad-b7d7-6b6502a7944e.png)  

Before I try to injection my idea in this code, I wanted to reproduce the orignal model performance as you mentioned in the paper. But I've been being struggling with it. So, If you don't mind plz give me some advise about reproducing the model.  
  
Here is what my experiment setting is.
- Using the preprocessed data shared on your google drive.

- Dataset sports
- n_users 35598
- n_items 18357
- n_interactions 268244  
-----------------------------
- lr 1e-5
- embed_size 64
- layers 2
- lambda_coeff=0.9
- cf_model 'lightgcn'
- mess_dropout=[0.1, 0.1]
- regs=[1e-4, 1e-4, 1e-2]
- sparse=1
- loss_ratio=0.03
- norm_type='sym'
-----------------------------
This is my best score i got
![image](https://user-images.githubusercontent.com/63500940/165429543-d62fe9de-61b4-4d84-9daf-7fe38293dbe4.png)  
  
Best regards.
Hoyoon.

**Comment by JinghaoZ** [comment]
Hello, thanks for your attention to our work.

I guess you have set the argument 'core' to 0, which is the cold-start setting. You can switch it to 5 to reproduce the warm-start performances.

Best regards.

**Comment by radium1234** [comment]
你好 我自己修改的在亚马逊数据集上grcn和mmgcn的模型的准确率要高于论文中数据，请问可不可以得到一份您修改过的可以用于亚马逊数据集推荐的grcn和mmgcn的代码？
