### ISSUE TITLE
请求一份baseline的代码

### ISSUE THREAD

**Issue by radium1234** [CRIPAC-DIG/MICRO#2]
您好！我自己修改了在亚马逊和mmgcn的模型的数据集上grcn和mmgcn的模型的准确率要计算论文中的数据，请不要让你过的可以得到用于亚马逊数据集推荐的gcn和mmgcn的代码？

**Comment by JinghaoZ** [comment]
您好！我们没有修改MMGCN和GRCN的代码，而是按照他们的数据格式处理数据集，在他们的源码上进行的实验。

**Comment by radium1234** [comment]
MICRO和LATTICE模型上的报告的数据不一致，想请教一下是什么原因？谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月9日(周一) 上午9:09
收件人: ***@***.***&gt;;
抄送: "Lei ***@***.******@***.***&gt;;
主题: Re: [CRIPAC-DIG/MICRO] 请求一份baseline的代码 (Issue #2)




 
您好！我们没有修改MMGCN和GRCN的代码，而是按照他们的数据格式处理数据集，在他们的源码上进行的实验。

**Comment by JinghaoZ** [comment]
您好！没有理解您说的是什么数据不一致？能否再说的详细一点

**Comment by JinghaoZ** [comment]
> MICRO和LATTICE模型上的报告的数据不一致，想请教一下是什么原因？谢谢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月9日(周一) 上午9:09 收件人: ***@***.***&gt;; 抄送: "Lei ***@***.******@***.***&gt;; 主题: Re: [CRIPAC-DIG/MICRO] 请求一份baseline的代码 (Issue #2) 您好！我们没有修改MMGCN和GRCN的代码，而是按照他们的数据格式处理数据集，在他们的源码上进行的实验。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

> MICRO和LATTICE模型上的报告的数据不一致，想请教一下是什么原因？谢谢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月9日(周一) 上午9:09 收件人: ***@***.***&gt;; 抄送: "Lei ***@***.******@***.***&gt;; 主题: Re: [CRIPAC-DIG/MICRO] 请求一份baseline的代码 (Issue #2) 您好！我们没有修改MMGCN和GRCN的代码，而是按照他们的数据格式处理数据集，在他们的源码上进行的实验。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


您好！没有理解您说的是什么数据不一致？能否再说的详细一点
