### ISSUE TITLE
The questions about processing datasets.

### ISSUE THREAD

**Issue by paulpig** [CRIPAC-DIG/MICRO#3]
Hi, authors.
Utilizing the processed datasets can reproduce the results reported in your paper.
However, when I rebuild needed datasets based on the raw data (e.g, reviews_Sports_and_Outdoors_5) by released codes (i.e., build_data.py), the performance is reduced severely.
Therefore, can you provide the remaining files like 'user-item-dict.json', 'user_list.txt', and 'item_list.txt' of the three datasets?

**Comment by JinghaoZ** [comment]
Hello!
I have uploaded relevant files to [Google Drive](https://drive.google.com/drive/folders/1sFg9W2wCexWahjqtN6MVc4f4dMj5hyFp). I guess the problem may be the wrong version of the dataset?  We used the old version of [Amazon review dataset](http://jmcauley.ucsd.edu/data/amazon/links.html) .
